# Generated by Django 3.1.4 on 2020-12-24 07:49

import classroom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=classroom.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=classroom.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
